# Generated by Django 5.2.9 on 2025-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.PositiveIntegerField(blank=True, help_text='Введите ID чата в телеграмм', null=True, verbose_name='ID чата в телеграмм'),
        ),
    ]
