# Generated by Django 5.2.9 on 2025-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="duration",
            field=models.DurationField(
                help_text="Укажите время в секундах, которое предположительно потратите на выполнение привычки.",
                verbose_name="Длительность выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки для напоминания в днях",
                verbose_name="Периодичность",
            ),
        ),
    ]
