# Generated by Django 5.2.9 on 2025-12-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habits_next_due_date_alter_habits_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="next_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Следующая дата выполнения"),
        ),
    ]
