# Generated by Django 5.2.9 on 2025-12-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habits_next_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HourlyTasks',
            new_name='HabitsForToday',
        ),
    ]
