# Generated by Django 5.2.9 on 2025-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_rename_hourlytasks_habitsfortoday"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitsfortoday",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Статус отправки"),
        ),
    ]
