# Generated by Django 5.2.9 on 2025-12-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habitsfortoday_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitsfortoday',
            name='sent',
        ),
    ]
