# Generated by Django 5.2.9 on 2026-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_remove_habitsfortoday_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Укажите можно ли опубликовать привычку в общий доступ.",
                verbose_name="Признак публичности",
            ),
        ),
    ]
